### ISSUE TITLE
[S2 - PBI11] Membuat halaman update data dokter untuk admin

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#16]
Deskripsi ada di komentar

**Comment by FiliaEunikeSologia** [comment]
**User Stories**
Sebagai admin, saya ingin memperbarui data dokter yang ada sehingga sistem akan menampilkan halaman untuk update data dokter 

**Activity Diagram**
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/f8b5a908-5b28-4a95-9861-48ce4266b6a0)

**Mockup**
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/e6846862-bd09-43a5-aa27-08ad4c50edf2)
