### ISSUE TITLE
[S2 - PBI15] Membuat halaman update jadwal dokter

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#20]
Deskripsi ada di komentar

**Comment by FiliaEunikeSologia** [comment]
**Activity Diagram**
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/b7657231-fbad-42a5-9b49-9bf235c9789b)
