### ISSUE TITLE
[S2 - PBI17] Membuat halaman lihat jadwal dokter dan poli

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#22]
Deskripsi ada di komentar

**Comment by FiliaEunikeSologia** [comment]
Activity Diagram
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/0050a293-9283-43f6-bafc-ccc33167c9a3)
