### ISSUE TITLE
[S2 - PBI21] Membuat halaman read detail obat yang akan diambil

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#26]
Deskripsi ada di komentar

**Comment by FiliaEunikeSologia** [comment]
Activity Diagram

![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/dd9131d4-ef48-43c5-a0c4-b69fc2d23e4b)
