### ISSUE TITLE
[S3 - PBI22] Membuat halaman cek reservasi pasien

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#27]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin mengecek reservasi, sehingga sistem dapat menampilkan halaman cek reservasi

Activity Diagram
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/a8dea009-2d65-4fb2-8812-f10fd6e99f45)

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/10a1c7b4-232e-455b-8d95-cc7adcbaf3e9)
