### ISSUE TITLE
[S3 - PBI23] Membuat halaman informasi reservasi pasien

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#28]

**Comment by FiliaEunikeSologia** [comment]
Sebagi pasien, saya ingin melihat informasi reservasi, sehingga sistem dapat menampilkan halaman informasi reservasi yang sudah ada di database

Activity Diagram


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/df64706d-1132-499e-83b9-e9b274d4ad98)

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/cd6576e5-bc2d-4b02-813b-122bd2953ec0)
