### ISSUE TITLE
[S3 - PBI24] Membuat halaman detail status reservasi pasien

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#29]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin melihat detail status reservasi, sehingga sistem dapat menampilkan halaman detail dari status reservasi 

Activity Diagram


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/fc7b2e63-470d-4809-badc-f4264278ac0e)

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/0b8d1208-261b-44e7-a442-1bcd3c59eed2)
