### ISSUE TITLE
[S3 - PBI25] Membuat halaman cetak invoice reservasi

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#30]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin, melihat halaman cetak invoice reservasi sehingga sistem dapat menampilkan halaman cetak invoice reservasi

Activity Diagram
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/f3e683da-a520-4833-85dd-593d69c993f0)

Mockup 
a. Invoice sudah verifikasi
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/8e3faac8-f004-48e8-b3ce-bb2c64b64455)

b. Invoice belum verifikasi
![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/ae16be6b-5574-43c3-ba80-c5c66d585e74)
