### ISSUE TITLE
[S3 - PBI26] Membuat halaman update reservasi pasien

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#31]

**Comment by FiliaEunikeSologia** [comment]
Sebagai admin, saya ingin melakukan update terhadap status reservasi yang telah dibuat oleh pasien sehingga akan ditampilkan halaman untuk melakukan update terhadap reservasi pasien

Activity Diagram

![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/e9045f55-3c4e-4416-bad8-e4cdd46e5935)


Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/46a6b576-c800-4038-af1a-6cd7d22f5af2)
