### ISSUE TITLE
[S3 - PBI27] Membuat halaman cek informasi pengambilan obat

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#32]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin Melakukan pengecekan informasi pengambilan obat sehingga sistem dapat menampilkan halaman cek pengambilan obat

Activity Diagram


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/6f1d561e-0894-4a3e-a118-95037e47b4c1)


Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/36013670-416c-4b86-958e-62b42f3093bb)
