### ISSUE TITLE
[S3 - PBI28] Membuat halaman informasi obat (daftar obat sesuai kode reservasi)

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#33]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, Saya ingin melihat informasi obat sehingga sistem dapat menampilkan halaman informasi obat

Acrtivity Diagram


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/ddab10c7-713c-485e-a211-c16b8492215b)

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/71013eff-d47f-499d-9d2b-b1b397be348f)
