### ISSUE TITLE
[S3 - PBI29] Membuat halaman detail obat pasien

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#34]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin melihat halaman detail obat pasien sehingga sistem dapat menampilkan halaman detail obat pasien

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/5b39045a-b611-4d58-aebe-81a072bbfaef)



![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/ec136536-40b1-4e6f-aac0-ae289a10c7c0)
