### ISSUE TITLE
[S3 - PBI30] Membuat halaman cetak resep obat

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#35]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin melakukan cetak resep obat sehingga sistem dapat manampilkan halaman detail status reservasi

Activity Diagram


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/38a8b235-5ccb-43b4-b8d5-71bc46742dc7)

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/a958a792-cbc6-4081-b017-e482b51046c4)
