### ISSUE TITLE
[S3 - PBI31] Membuat halaman untuk input keluhan yang dirasakan

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#36]

**Comment by FiliaEunikeSologia** [comment]
Sebagai pasien, saya ingin, melihat halaman keluhan yang dirasakan sehingga sistem dapat menampilkan halaman untuk mengisikan keluhan pasien

Mockup


![Image](https://github.com/SI-RPL-2023/SI4408_F_SIGMA-HEALTH/assets/115911698/242154ca-ddbb-4de9-9822-dfa4d8d725b6)
