### ISSUE TITLE
[S1 - PBI5] Membuat halaman create poli

### ISSUE THREAD

**Issue by Alfarezie** [SI-RPL-2023/SI4408_F_SIGMA-HEALTH#5]
Sebagai admin, saya ingin melakukan create poli sehingga akan ditampilkan halaman create poli.

Activity Diagram

![Image](https://user-images.githubusercontent.com/127197844/229340335-650063b1-e764-4253-a2d3-2b7ea90f6885.png)

Mock up halaman
![Image](https://user-images.githubusercontent.com/127197844/229340073-97228120-78a9-4825-a6f8-9d7b4a04fa41.png)

**Comment by FikriFathoni** [comment]
Resolve
